<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260329181735 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alerts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rule_id VARCHAR(100) NOT NULL, rule_name VARCHAR(255) NOT NULL, severity VARCHAR(20) NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(30) NOT NULL, triggering_event_id UUID DEFAULT NULL, related_event_ids JSON NOT NULL, ai_analysis JSON DEFAULT NULL, incident_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE incidents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, severity VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, alert_ids JSON NOT NULL, ai_remediation JSON DEFAULT NULL, timeline JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE monitoring_config (id INT NOT NULL, monitored_interfaces JSON NOT NULL, monitored_subnets JSON NOT NULL, excluded_ips JSON NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE network_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, src_ip VARCHAR(45) NOT NULL, dst_ip VARCHAR(45) NOT NULL, src_port INT DEFAULT NULL, dst_port INT DEFAULT NULL, protocol VARCHAR(10) NOT NULL, bytes_sent INT NOT NULL, direction VARCHAR(20) NOT NULL, interface VARCHAR(50) NOT NULL, flags VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, rule_type VARCHAR(50) NOT NULL, severity VARCHAR(20) NOT NULL, config JSON NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE alerts');
        $this->addSql('DROP TABLE incidents');
        $this->addSql('DROP TABLE monitoring_config');
        $this->addSql('DROP TABLE network_events');
        $this->addSql('DROP TABLE rules');
    }
}
